from groq import Groq
from dotenv import load_dotenv
import os

load_dotenv()

client = Groq(
    api_key=os.getenv("CRIME_GROQ_API_KEY")
)


def build_prompt(data: dict) -> str:
    return f"""
You are an AI Crime Intelligence Officer working for the Karnataka State Police.

You are NOT a chatbot.

You are analysing crime analytics generated by the KAVACH platform.

Your task is to generate a professional intelligence report.

Use ONLY the information provided.

The report must contain the following headings:

## Crime Summary

## Evidence

## Pattern Analysis

## Risk Assessment

## Recommended Police Actions

## Confidence Level

Keep the report concise, factual and suitable for police officers.

Crime Analytics:

{data}
"""


def analyze(data: dict):

    prompt = build_prompt(data)

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": "You are a professional police crime intelligence analyst."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.3,
        max_tokens=700
    )

    return {
        "report": response.choices[0].message.content
    }