"""
prompt_builder.py

Builds a structured intelligence prompt for the LLM.

The analytics engines perform all calculations.

This module only converts structured intelligence into
a prompt suitable for Groq.
"""


# ==========================================================
# FORECAST FORMATTER
# ==========================================================

def format_forecast(forecast):

    if forecast is None:
        return "No forecast available."

    text = []

    text.append("=== FORECAST INTELLIGENCE ===")

    text.append(
        f"Overall Risk: {forecast['overall_risk']}"
    )

    text.append(
        f"Confidence: {forecast['confidence']}%"
    )

    text.append("")

    text.append("Predicted Crimes:")

    for crime in forecast["crime_forecast"][:3]:

        text.append(

            f"- {crime['crime']} | "
            f"Probability {crime['probability']}% | "
            f"{crime['likely_location']} | "
            f"{crime['peak_period']} | "
            f"Deployment: {crime['recommended_deployment']}"

        )

    text.append("")

    return "\n".join(text)


# ==========================================================
# PATTERN FORMATTER
# ==========================================================

def format_patterns(patterns):

    if patterns is None:
        return "No pattern intelligence available."

    text = []

    text.append("=== CRIME PATTERN INTELLIGENCE ===")

    summary = patterns["executive_summary"]

    text.append(
        f"Threat Level: {summary['overall_threat']}"
    )

    text.append(
        f"Dominant Crime: {summary['dominant_crime']}"
    )

    text.append("")

    text.append("Organized Crime:")

    for gang in patterns["organized_crime"][:3]:

        text.append(

            f"- {gang['suspect_group']} | "
            f"{gang['total_cases']} cases | "
            f"Threat {gang['threat_level']}"

        )

    text.append("")

    text.append("Behaviour Profiles:")

    for profile in patterns["crime_behaviour_profiles"][:3]:

        text.append(

            f"- {profile['crime']} | "
            f"{profile['modus_operandi']} | "
            f"{profile['preferred_locations'][0]} | "
            f"{profile['peak_period']}"

        )

    text.append("")

    return "\n".join(text)


# ==========================================================
# ANOMALY FORMATTER
# ==========================================================

def format_anomalies(anomalies):

    if anomalies is None:
        return "No anomaly report available."

    text = []

    text.append("=== ANOMALY INTELLIGENCE ===")

    summary = anomalies["executive_summary"]

    text.append(
        f"Threat Level: {summary['overall_threat']}"
    )

    text.append(
        f"Detected Anomalies: {summary['total_anomalies']}"
    )

    text.append("")

    if len(anomalies["anomalies"]) == 0:

        text.append(
            "No significant anomalies detected."
        )

    else:

        for anomaly in anomalies["anomalies"][:5]:

            text.append(

                f"- {anomaly['anomaly_type']} | "
                f"{anomaly['severity']} | "
                f"{anomaly['reason']}"

            )

    text.append("")

    return "\n".join(text)

# ==========================================================
# PROMPT BUILDER
# ==========================================================

def build_prompt(forecast, patterns, anomalies):

    forecast_text = format_forecast(forecast)

    pattern_text = format_patterns(patterns)

    anomaly_text = format_anomalies(anomalies)

    prompt = f"""
You are an experienced Police Crime Intelligence Officer.

You have been provided with structured crime intelligence generated by analytical models.

IMPORTANT RULES

- DO NOT invent facts.
- DO NOT assume information not provided.
- Use ONLY the supplied intelligence.
- Keep the report professional and operational.
- Maximum 300 words.

Your report must use EXACTLY the following Markdown headings.

Do NOT number the headings.
Do NOT rename the headings.
Do NOT use bold formatting for the headings.

## Executive Summary

## Overall Threat Assessment

## Key Criminal Patterns

## Immediate Operational Priorities

## Patrol & Deployment Recommendations

## Officer Advisory

====================================================

STATION:
{forecast["station"]}

====================================================

{forecast_text}

====================================================

{pattern_text}

====================================================

{anomaly_text}

====================================================

Generate the operational intelligence report now.

Requirements:
- Use the headings exactly as provided above.
- Base every statement only on the supplied analytics.
- Keep the tone suitable for senior police officers.
- Do not include introductory or concluding remarks.
- If a section has no supporting evidence, explicitly state "No significant findings."

"""

    return prompt