// ExplainableAI.tsx
import { useCallback, useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { useAuthStore } from "../store/authStore";

const API_BASE = "https://prakalpa-backend.onrender.com/api/v1";

// ---------- Types ----------

/** Shapes of dashboard.py / patterns.py / anomaly.py / zone.py / forecast.py
 * outputs aren't visible from the frontend, so these payloads are rendered
 * generically (see <Register/> below) instead of guessed field-by-field. */
type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [k: string]: JsonValue };
type JsonRecord = Record<string, JsonValue>;

interface AiSummaryResponse {
  summary: string;
}

interface AiReportResponse {
  station: string;
  report: string;
  analytics: JsonRecord;
}

interface Fetchable<T> {
  data: T | null;
  loading: boolean;
  error: string;
}

const initialFetchable = <T,>(): Fetchable<T> => ({
  data: null,
  loading: false,
  error: "",
});

// ---------- Translations ----------

const translations = {
  en: {
    portalSub: "OFFICER PORTAL",
    signOut: "Sign out",
    navDashboard: "Dashboard",
    navBNS: "BNS Sections",
    navCrime: "Crime Hotspot",
    navExplain: "Explainable AI",
    navSettings: "Settings",
    navGenerate: "Generate report",
    switchLang: "ಕನ್ನಡ",
    topbarTitle: "Explainable AI",
    topbarSub: "Station intelligence, grounded in the analytics that produced it",
    stationPlaceholder: "Station name, e.g. Jayanagar PS",
    loadReport: "Load station report",
    emptyState:
      "Enter a station above to pull its forecast, zone summary, patterns, and anomalies together.",
    stationInsights: "Station Insights",
    subtitleZone: "Jurisdictional breakdown for this station",
    subtitlePatterns: "Recurring MO & timing",
    subtitleAnomalies: "Deviation from baseline",
    tabZone: "Zone Summary",
    tabPatterns: "Patterns",
    tabAnomalies: "Anomalies",
    tabForecast: "Crime Forecast",
    tabHotspots: "Hotspots",
    tabTiming: "Timing",
    tabDeployment: "Deployment",
    tabRisk: "Risk Factors",
    aiAssessment: "AI Assessment",
    disclaimerPre: "Generated by llama-3.3-70b-versatile from",
    disclaimerMid: "'s analytics only · decision-support, officer verification required",
    patternSummaryBtn: "Pattern summary",
    summarizing: "Summarizing…",
    fullReportBtn: "Full report",
    drafting: "Drafting…",
    patternSummaryLabel: "Pattern Summary",
    reportLabel: "Operational Intelligence Report",
    showEvidence: "Show evidence used",
    hideEvidence: "Hide evidence used",
    evidenceHeading: "Evidence used for this report",
    aiEngineOnline: "AI Engine Online",
    forecastFallbackPeriod: "7-day forecast",
    statConfidence: "Confidence",
    statCrimesTracked: "Crimes tracked",
    statHistoricalCases: "Historical cases",
    statCrimeTypes: "Crime types",
    tagLocation: "Location",
    tagPeak: "Peak",
    tagVehicle: "Vehicle",
    tagUnit: "Unit",
    casesSuffix: "cases",
    patrolLabel: "Patrol:",
    noData: "No data returned.",
    loadingLabel: "Loading…",
    zoneTopCrime: "Top crime",
    zonePeakTime: "Peak time",
    zoneWeather: "Weather",
    zoneRiskScore: "Risk score",
    zoneCrimeBreakdown: "Crime Breakdown",
    zoneReasoning: "Reasoning",
    zoneFestival: "Festival",
    zoneCaseLink: "Case link",
    patStatThreat: "Threat",
    patStatDominant: "Dominant",
    patStatHotspot: "Hotspot",
    patStatHighPriority: "High-priority",
    behaviourProfiles: "Behaviour Profiles",
    patPatternType: "Pattern type",
    patFrequency: "Frequency",
    patSuspectGroup: "Suspect group",
    patSuspectVehicle: "Suspect vehicle",
    patLinkedCluster: "Linked cluster",
    patPatrolPriority: "Patrol priority",
    patPreferredLocations: "Preferred Locations",
    patActSections: "Act Sections",
    patRecommended: "Recommended:",
    patOperationalAlert: "Operational Alert",
    confSuffix: "conf",
    anomStatCritical: "Critical",
    anomStatHigh: "High",
    anomStatTotal: "Total",
    changeSuffix: "change",
  },
  kn: {
    portalSub: "ಅಧಿಕಾರಿ ಪೋರ್ಟಲ್",
    signOut: "ಸೈನ್ ಔಟ್",
    navDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    navBNS: "ಬಿಎನ್‌ಎಸ್ (BNS) ವಿಭಾಗಗಳು",
    navCrime: "ಅಪರಾಧ ತೀವ್ರತೆಯ ತಾಣ",
    navExplain: "ವಿವರಿಸಬಹುದಾದ AI",
    navSettings: "ಸಂಯೋಜನೆಗಳು",
    navGenerate: "ವರದಿಯನ್ನು ರಚಿಸಿ",
    switchLang: "English",
    topbarTitle: "ವಿವರಿಸಬಹುದಾದ AI",
    topbarSub: "ಠಾಣಾ ಗುಪ್ತಚರ ಮಾಹಿತಿ, ಅದನ್ನು ಉತ್ಪಾದಿಸಿದ ವಿಶ್ಲೇಷಣೆಯ ಆಧಾರದ ಮೇಲೆ",
    stationPlaceholder: "ಠಾಣೆ ಹೆಸರು, ಉದಾ. ಜಯನಗರ ಠಾಣೆ",
    loadReport: "ಠಾಣಾ ವರದಿ ಲೋಡ್ ಮಾಡಿ",
    emptyState:
      "ಮೇಲೆ ಒಂದು ಠಾಣೆ ನಮೂದಿಸಿ, ಅದರ ಮುನ್ಸೂಚನೆ, ವಲಯ ಸಾರಾಂಶ, ಮಾದರಿಗಳು ಮತ್ತು ಅಸಹಜತೆಗಳನ್ನು ಒಟ್ಟಿಗೆ ಪಡೆಯಲು.",
    stationInsights: "ಠಾಣಾ ಒಳನೋಟಗಳು",
    subtitleZone: "ಈ ಠಾಣೆಗೆ ಸಂಬಂಧಿಸಿದ ಅಧಿಕಾರ ವ್ಯಾಪ್ತಿಯ ವಿಭಜನೆ",
    subtitlePatterns: "ಪುನರಾವರ್ತಿತ ಕಾರ್ಯವಿಧಾನ ಮತ್ತು ಸಮಯ",
    subtitleAnomalies: "ಮೂಲಮಟ್ಟದಿಂದ ವ್ಯತ್ಯಾಸ",
    tabZone: "ವಲಯ ಸಾರಾಂಶ",
    tabPatterns: "ಮಾದರಿಗಳು",
    tabAnomalies: "ಅಸಹಜತೆಗಳು",
    tabForecast: "ಅಪರಾಧ ಮುನ್ಸೂಚನೆ",
    tabHotspots: "ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು",
    tabTiming: "ಸಮಯ",
    tabDeployment: "ನಿಯೋಜನೆ",
    tabRisk: "ಅಪಾಯ ಅಂಶಗಳು",
    aiAssessment: "AI ಮೌಲ್ಯಮಾಪನ",
    disclaimerPre: "llama-3.3-70b-versatile ಮೂಲಕ",
    disclaimerMid: "ರ ವಿಶ್ಲೇಷಣೆಯಿಂದ ಮಾತ್ರ ರಚಿಸಲಾಗಿದೆ · ನಿರ್ಧಾರ-ಬೆಂಬಲ, ಅಧಿಕಾರಿ ಪರಿಶೀಲನೆ ಅಗತ್ಯ",
    patternSummaryBtn: "ಮಾದರಿ ಸಾರಾಂಶ",
    summarizing: "ಸಾರಾಂಶಿಸಲಾಗುತ್ತಿದೆ…",
    fullReportBtn: "ಪೂರ್ಣ ವರದಿ",
    drafting: "ರಚಿಸಲಾಗುತ್ತಿದೆ…",
    patternSummaryLabel: "ಮಾದರಿ ಸಾರಾಂಶ",
    reportLabel: "ಕಾರ್ಯಾಚರಣಾ ಗುಪ್ತಚರ ವರದಿ",
    showEvidence: "ಬಳಸಿದ ಪುರಾವೆ ತೋರಿಸಿ",
    hideEvidence: "ಬಳಸಿದ ಪುರಾವೆ ಮರೆಮಾಡಿ",
    evidenceHeading: "ಈ ವರದಿಗೆ ಬಳಸಿದ ಪುರಾವೆ",
    aiEngineOnline: "AI ಎಂಜಿನ್ ಆನ್‌ಲೈನ್",
    forecastFallbackPeriod: "7-ದಿನಗಳ ಮುನ್ಸೂಚನೆ",
    statConfidence: "ವಿಶ್ವಾಸಾರ್ಹತೆ",
    statCrimesTracked: "ಟ್ರ್ಯಾಕ್ ಮಾಡಿದ ಅಪರಾಧಗಳು",
    statHistoricalCases: "ಐತಿಹಾಸಿಕ ಪ್ರಕರಣಗಳು",
    statCrimeTypes: "ಅಪರಾಧ ಮಾದರಿಗಳು",
    tagLocation: "ಸ್ಥಳ",
    tagPeak: "ಗರಿಷ್ಠ ಸಮಯ",
    tagVehicle: "ವಾಹನ",
    tagUnit: "ಘಟಕ",
    casesSuffix: "ಪ್ರಕರಣಗಳು",
    patrolLabel: "ಗಸ್ತು:",
    noData: "ಯಾವುದೇ ಮಾಹಿತಿ ಸಿಗಲಿಲ್ಲ.",
    loadingLabel: "ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
    zoneTopCrime: "ಪ್ರಮುಖ ಅಪರಾಧ",
    zonePeakTime: "ಗರಿಷ್ಠ ಸಮಯ",
    zoneWeather: "ಹವಾಮಾನ",
    zoneRiskScore: "ಅಪಾಯ ಅಂಕ",
    zoneCrimeBreakdown: "ಅಪರಾಧ ವಿಭಜನೆ",
    zoneReasoning: "ಕಾರಣ",
    zoneFestival: "ಹಬ್ಬ",
    zoneCaseLink: "ಪ್ರಕರಣ ಸಂಪರ್ಕ",
    patStatThreat: "ಬೆದರಿಕೆ",
    patStatDominant: "ಪ್ರಧಾನ",
    patStatHotspot: "ಹಾಟ್‌ಸ್ಪಾಟ್",
    patStatHighPriority: "ಹೆಚ್ಚಿನ ಆದ್ಯತೆ",
    behaviourProfiles: "ವರ್ತನಾ ಪ್ರೊಫೈಲ್‌ಗಳು",
    patPatternType: "ಮಾದರಿ ಪ್ರಕಾರ",
    patFrequency: "ಆವರ್ತನ",
    patSuspectGroup: "ಶಂಕಿತ ಗುಂಪು",
    patSuspectVehicle: "ಶಂಕಿತ ವಾಹನ",
    patLinkedCluster: "ಸಂಪರ್ಕಿತ ಕ್ಲಸ್ಟರ್",
    patPatrolPriority: "ಗಸ್ತು ಆದ್ಯತೆ",
    patPreferredLocations: "ಆದ್ಯತೆಯ ಸ್ಥಳಗಳು",
    patActSections: "ಕಾಯ್ದೆ ವಿಭಾಗಗಳು",
    patRecommended: "ಶಿಫಾರಸು:",
    patOperationalAlert: "ಕಾರ್ಯಾಚರಣಾ ಎಚ್ಚರಿಕೆ",
    confSuffix: "ವಿಶ್ವಾಸ",
    anomStatCritical: "ಗಂಭೀರ",
    anomStatHigh: "ಹೆಚ್ಚಿನ",
    anomStatTotal: "ಒಟ್ಟು",
    changeSuffix: "ಬದಲಾವಣೆ",
  },
} as const;

type Lang = keyof typeof translations;

// ---------- Component ----------

export default function ExplainableAI() {
  const { user, logout } = useAuthStore();
  const navigate = useNavigate();

  const [lang, setLang] = useState<Lang>("en");
  const t = translations[lang];
  const toggleLanguage = () => setLang((prev) => (prev === "en" ? "kn" : "en"));

  const officerName = user?.name || "Unknown Officer";
  const officerBadge = user?.badge || "";

  const [station, setStation] = useState("");
  const [submittedStation, setSubmittedStation] = useState("");

  // Station-scoped — loaded together, rendered together, on one page
  const [forecast, setForecast] =
    useState<Fetchable<JsonValue>>(initialFetchable());
  const [zone, setZone] = useState<Fetchable<JsonValue>>(initialFetchable());
  const [patterns, setPatterns] =
    useState<Fetchable<JsonValue>>(initialFetchable());
  const [anomalies, setAnomalies] =
    useState<Fetchable<JsonValue>>(initialFetchable());

  // AI assessment
  const [summary, setSummary] =
    useState<Fetchable<AiSummaryResponse>>(initialFetchable());
  const [report, setReport] =
    useState<Fetchable<AiReportResponse>>(initialFetchable());
  const [showEvidence, setShowEvidence] = useState(false);

  // ---- View-only UI state (new layout). No fetch logic touched. ----
  const [forecastTab, setForecastTab] = useState<
    "forecast" | "hotspots" | "timing" | "deployment" | "risk"
  >("forecast");
  const [openProfile, setOpenProfile] = useState<number | null>(0);
  const [insightTab, setInsightTab] = useState<
    "zone" | "patterns" | "anomalies"
  >("zone");

  const runStationReport = useCallback((stationName: string) => {
    if (!stationName.trim()) return;
    setSubmittedStation(stationName.trim());

    const load = (path: string, setter: (v: Fetchable<JsonValue>) => void) => {
      setter({ data: null, loading: true, error: "" });
      axios
        .get(`${API_BASE}${path}`)
        .then((res) => setter({ data: res.data, loading: false, error: "" }))
        .catch((err) =>
          setter({ data: null, loading: false, error: describeError(err) }),
        );
    };

    load(`/forecast/${encodeURIComponent(stationName.trim())}`, setForecast);
    load(`/zone/${encodeURIComponent(stationName.trim())}`, setZone);
    load(`/patterns/${encodeURIComponent(stationName.trim())}`, setPatterns);
    load(`/anomalies/${encodeURIComponent(stationName.trim())}`, setAnomalies);

    // Reset any previous AI output — it belongs to the old station
    setSummary(initialFetchable());
    setReport(initialFetchable());
    setShowEvidence(false);
  }, []);

  const runSummary = () => {
    if (!submittedStation) return;
    setSummary({ data: null, loading: true, error: "" });
    axios
      .post(
        `${API_BASE}/pattern-summary/${encodeURIComponent(submittedStation)}`,
      )
      .then((res) => setSummary({ data: res.data, loading: false, error: "" }))
      .catch((err) =>
        setSummary({ data: null, loading: false, error: describeError(err) }),
      );
  };

  const runReport = () => {
    if (!submittedStation) return;
    setReport({ data: null, loading: true, error: "" });
    axios
      .post(`${API_BASE}/ai-summary/${encodeURIComponent(submittedStation)}`)
      .then((res) => setReport({ data: res.data, loading: false, error: "" }))
      .catch((err) =>
        setReport({ data: null, loading: false, error: describeError(err) }),
      );
  };

  const S = styles;

  return (
    <div style={S.page}>
      <style>{keyframes}</style>

      {/* ---------------- SIDEBAR ---------------- */}
      <aside style={S.sidebar}>
        <div style={S.sidebarLogoRow}>
          <div style={S.sidebarLogoIcon}>
            <ShieldIcon size={18} color="#FFFFFF" />
          </div>
          <div>
            <div style={S.sidebarLogoTitle}>KAVACH</div>
            <div style={S.sidebarLogoSub}>{t.portalSub}</div>
          </div>
        </div>

        <nav style={S.navList}>
          {[
            {
              key: "dashboard",
              label: t.navDashboard,
              path: "/officer/dashboard",
              icon: "grid",
            },
            {
              key: "cases",
              label: t.navBNS,
              path: "/bns",
              icon: "case",
            },
            { key: "districts", label: t.navCrime, path: "/dash", icon: "map" },
            {
              key: "analytics",
              label: t.navExplain,
              path: "/explain",
              icon: "chart",
            },
            {
              key: "reports",
              label: t.navGenerate,
              path: "/generate-report",
              icon: "bolt",
            },
            {
              key: "settings",
              label: t.navSettings,
              path: "/settings",
              icon: "gear",
            },
          ].map((item) => (
            <button
              key={item.key}
              type="button"
              onClick={() => navigate(item.path)}
              style={S.navItem(item.key === "analytics")}
            >
              <NavIcon
                name={item.icon}
                color={
                  item.key === "analytics"
                    ? "#FFFFFF"
                    : "rgba(255,255,255,0.55)"
                }
              />
              {item.label}
            </button>
          ))}

        
        </nav>

        <div style={S.sidebarFooter}>
          <div style={S.sidebarOfficerRow}>
            <div style={S.sidebarAvatar}>
              {(officerName || "O").charAt(0).toUpperCase()}
            </div>
            <div style={{ minWidth: 0 }}>
              <div style={S.sidebarOfficerName}>{officerName}</div>
              <div style={S.sidebarOfficerBadge}>{officerBadge}</div>
            </div>
          </div>
          <button
            type="button"
            onClick={() => {
              logout();
              navigate("/");
            }}
            style={S.logoutBtn}
          >
            <NavIcon name="logout" color="rgba(255,255,255,0.7)" />
            {t.signOut}
          </button>
        </div>
      </aside>

      {/* ---------------- MAIN ---------------- */}
      <div style={S.main}>
        <div style={S.topbar}>
          <div>
            <div style={S.topbarTitle}>{t.topbarTitle}</div>
            <div style={S.topbarSub}>{t.topbarSub}</div>
          </div>
          <div style={S.officerChipRow}>
            <button onClick={toggleLanguage} type="button" style={S.langBtn}>
              <GlobeIcon color="#0E8C8C" size={13} />
              {t.switchLang}
            </button>
            <span style={S.officerBadge}>{officerBadge}</span>
            <span style={S.officerName}>{officerName}</span>
          </div>
        </div>

        <div style={S.body}>
          {/* ---------- Station lookup ---------- */}
          <div style={S.stationBar}>
            <input
              style={S.stationInput}
              placeholder={t.stationPlaceholder}
              value={station}
              onChange={(e) => setStation(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") runStationReport(station);
              }}
            />
            <button
              style={S.primaryBtn}
              onClick={() => runStationReport(station)}
              disabled={!station.trim()}
            >
              {t.loadReport}
            </button>
          </div>

          {!submittedStation && (
            <div style={S.emptyState}>{t.emptyState}</div>
          )}

          {/* ---------- Zone / Patterns / Anomalies — one page, one grid ---------- */}
          {submittedStation && (
            <>
              <div style={S.panel}>
                <FetchState state={forecast} />
                {forecast.data != null && !forecast.loading && !forecast.error && (
                  <ForecastBlock
                    data={forecast.data}
                    tab={forecastTab}
                    setTab={setForecastTab}
                    fallbackStation={submittedStation}
                    t={t}
                  />
                )}
              </div>

              <div style={S.panel}>
                <div style={styles.panelTitle}>{t.stationInsights}</div>
                <div style={styles.panelSubtitle}>
                  {insightTab === "zone" && t.subtitleZone}
                  {insightTab === "patterns" && t.subtitlePatterns}
                  {insightTab === "anomalies" && t.subtitleAnomalies}
                </div>
                <div style={{ marginTop: 10 }}>
                  <TabStrip
                    active={insightTab}
                    onChange={setInsightTab}
                    tabs={[
                      {
                        key: "zone",
                        label: t.tabZone,
                        count: zone.data ? asRecArr(asRec(zone.data).crime_breakdown).length : undefined,
                      },
                      {
                        key: "patterns",
                        label: t.tabPatterns,
                        count: patterns.data
                          ? asRecArr(asRec(patterns.data).crime_behaviour_profiles).length
                          : undefined,
                      },
                      {
                        key: "anomalies",
                        label: t.tabAnomalies,
                        count: anomalies.data ? asRecArr(asRec(anomalies.data).anomalies).length : undefined,
                      },
                    ]}
                  />

                  {insightTab === "zone" && (
                    <>
                      <FetchState state={zone} />
                      {zone.data != null && !zone.loading && !zone.error && (
                        <ZoneBlock data={zone.data} t={t} />
                      )}
                    </>
                  )}

                  {insightTab === "patterns" && (
                    <>
                      <FetchState state={patterns} />
                      {patterns.data != null &&
                        !patterns.loading &&
                        !patterns.error && (
                          <PatternsBlock
                            data={patterns.data}
                            openProfile={openProfile}
                            setOpenProfile={setOpenProfile}
                            t={t}
                          />
                        )}
                    </>
                  )}

                  {insightTab === "anomalies" && (
                    <>
                      <FetchState state={anomalies} />
                      {anomalies.data != null &&
                        !anomalies.loading &&
                        !anomalies.error && <AnomaliesBlock data={anomalies.data} />}
                    </>
                  )}
                </div>
              </div>

              {/* ---------- AI Assessment ---------- */}
              <div style={S.aiSection}>
                <div style={S.aiSectionHead}>
                  <div>
                    <div style={S.resultsTitle}>{t.aiAssessment}</div>
                    <div style={S.disclaimer}>
                      {t.disclaimerPre} {submittedStation}
                      {t.disclaimerMid}
                    </div>
                  </div>
                  <div style={{ display: "flex", gap: 8 }}>
                    <button
                      style={S.secondaryBtn}
                      onClick={runSummary}
                      disabled={summary.loading}
                    >
                      {summary.loading ? t.summarizing : t.patternSummaryBtn}
                    </button>
                    <button
                      style={S.primaryBtn}
                      onClick={runReport}
                      disabled={report.loading}
                    >
                      {report.loading ? t.drafting : t.fullReportBtn}
                    </button>
                  </div>
                </div>

                {(summary.loading || summary.error || summary.data) && (
                  <div style={S.aiCard}>
                    <div style={S.aiCardLabel}>{t.patternSummaryLabel}</div>
                    <FetchState state={summary} />
                    {summary.data && !summary.loading && (
                      <MarkdownLite text={summary.data.summary} />
                    )}
                  </div>
                )}

                {(report.loading || report.error || report.data) && (
                  <div style={S.aiCard}>
                    <div style={S.aiCardLabel}>{t.reportLabel}</div>
                    <FetchState state={report} />
                    {report.data && !report.loading && (
                      <>
                        <MarkdownLite text={report.data.report} />
                        <button
                          style={S.evidenceToggle}
                          onClick={() => setShowEvidence((s) => !s)}
                        >
                          {showEvidence ? t.hideEvidence : t.showEvidence}
                        </button>
                        {showEvidence && (
                          <div style={S.evidenceBox}>
                            <div style={S.evidenceHeading}>
                              {t.evidenceHeading}
                            </div>
                            <Register data={report.data.analytics} />
                          </div>
                        )}
                      </>
                    )}
                  </div>
                )}
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

// ---------- Shared bits ----------

function describeError(err: unknown): string {
  if (axios.isAxiosError(err)) {
    if (err.code === "ERR_NETWORK")
      return "AI engine or backend is not reachable.";
    const detail = err.response?.data?.detail;
    if (typeof detail === "string") return detail;
    if (err.response?.status) return `Request failed (${err.response.status})`;
  }
  return "Something went wrong loading this data.";
}

function FetchState({ state }: { state: Fetchable<unknown> }) {
  if (state.loading) {
    return (
      <div style={styles.loadingState}>
        <div style={styles.spinner} />
        Loading…
      </div>
    );
  }
  if (state.error) {
    return <div style={styles.errorBox}>{state.error}</div>;
  }
  return null;
}

function Panel({
  title,
  subtitle,
  children,
}: {
  title: string;
  subtitle: string;
  children: React.ReactNode;
}) {
  return (
    <div style={styles.panel}>
      <div style={styles.panelTitle}>{title}</div>
      <div style={styles.panelSubtitle}>{subtitle}</div>
      <div style={{ marginTop: 10 }}>{children}</div>
    </div>
  );
}

/** Flat objects of primitives render as a label/value grid; arrays of
 * records render as wrapping cards (not one wide row per record — that's
 * what used to blow out the page width); anything else nested renders as
 * an indented list so it's still readable without knowing the exact schema
 * ahead of time. `level` only affects styling (top-level sections read as
 * headings), never the data itself. */
function Register({ data, level = 0 }: { data: JsonValue; level?: number }) {
  if (data === null || data === undefined) {
    return <div style={styles.emptyState}>No data returned.</div>;
  }

  if (typeof data !== "object") {
    return <div style={styles.registerValue}>{String(data)}</div>;
  }

  if (Array.isArray(data)) {
    if (data.length === 0) {
      return <div style={styles.emptyState}>No data returned.</div>;
    }

    const allRecords = data.every(
      (v) => v !== null && typeof v === "object" && !Array.isArray(v),
    );

    if (allRecords) {
      return (
        <div style={styles.evidenceCardGrid}>
          {data.map((v, i) => (
            <div key={i} style={styles.evidenceCard}>
              <div style={styles.evidenceCardIndex}>Item {i + 1}</div>
              <Register data={v} level={level + 1} />
            </div>
          ))}
        </div>
      );
    }

    // Array of primitives (or mixed) — a tag row reads better than an
    // index-keyed list.
    return (
      <div style={styles.tagRow}>
        {data.map((v, i) => (
          <span key={i} style={styles.evidenceTag}>
            {v === null ? "—" : String(v)}
          </span>
        ))}
      </div>
    );
  }

  const entries = Object.entries(data as JsonRecord);

  if (entries.length === 0) {
    return <div style={styles.emptyState}>No data returned.</div>;
  }

  const isFlat = entries.every(([, v]) => v === null || typeof v !== "object");

  if (isFlat) {
    return (
      <div style={styles.registerGrid}>
        {entries.map(([k, v]) => (
          <div key={k} style={styles.registerCell}>
            <div style={styles.registerLabel}>{formatLabel(k)}</div>
            <div style={styles.registerValue}>
              {v === null ? "—" : String(v)}
            </div>
          </div>
        ))}
      </div>
    );
  }

  return (
    <div style={styles.registerNested}>
      {entries.map(([k, v]) => (
        <div key={k} style={level === 0 ? styles.nestedSection : styles.nestedRow}>
          <div style={level === 0 ? styles.subHeading : styles.registerLabel}>
            {formatLabel(k)}
          </div>
          {v !== null && typeof v === "object" ? (
            <div style={level === 0 ? { marginTop: 8 } : styles.nestedIndent}>
              <Register data={v} level={level + 1} />
            </div>
          ) : (
            <div style={styles.registerValue}>
              {v === null ? "—" : String(v)}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}

function formatLabel(key: string): string {
  return key.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

// ---------- Safe accessors (defensive against schema drift) ----------

const asRec = (v: JsonValue | undefined | null): JsonRecord =>
  v && typeof v === "object" && !Array.isArray(v) ? (v as JsonRecord) : {};
const asArr = (v: JsonValue | undefined | null): JsonValue[] =>
  Array.isArray(v) ? v : [];
const asRecArr = (v: JsonValue | undefined | null): JsonRecord[] =>
  asArr(v).filter(
    (x) => x && typeof x === "object" && !Array.isArray(x),
  ) as JsonRecord[];
const asStr = (v: JsonValue | undefined | null): string =>
  v === null || v === undefined ? "" : String(v);
const asNum = (v: JsonValue | undefined | null): number =>
  typeof v === "number" ? v : Number(v) || 0;

// ---------- Risk / threat visual language ----------

function riskColor(risk: string): { fg: string; bg: string; bar: string } {
  const r = risk.trim().toLowerCase();
  if (r === "critical") return { fg: "#7A1F1F", bg: "#FBEBEA", bar: "#C94B4B" };
  if (r === "high" || r === "spike")
    return { fg: "#A13D1F", bg: "#FCEEE4", bar: "#E07A3E" };
  if (r === "medium")
    return { fg: "#8A6D00", bg: "#FBF3D6", bar: "#D9A80B" };
  if (r === "low" || r === "drop")
    return { fg: TEAL_DARK, bg: TEAL_TINT, bar: TEAL };
  return { fg: MUTED, bg: BG_SECTION, bar: MUTED };
}

function RiskBadge({ risk, big }: { risk: string; big?: boolean }) {
  if (!risk) return null;
  const c = riskColor(risk);
  return (
    <span
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: 5,
        padding: big ? "5px 12px" : "2px 8px",
        borderRadius: 999,
        background: c.bg,
        color: c.fg,
        fontWeight: 800,
        fontSize: big ? 13 : 10.5,
        letterSpacing: "0.03em",
        textTransform: "uppercase",
        whiteSpace: "nowrap",
      }}
    >
      <span
        style={{
          width: big ? 7 : 5,
          height: big ? 7 : 5,
          borderRadius: "50%",
          background: c.fg,
          display: "inline-block",
        }}
      />
      {risk}
    </span>
  );
}

function MiniStat({
  label,
  value,
  accent,
}: {
  label: string;
  value: string;
  accent?: boolean;
}) {
  return (
    <div style={styles.miniStat}>
      <div style={styles.miniStatLabel}>{label}</div>
      <div
        style={{
          ...styles.miniStatValue,
          color: accent ? TEAL_DARK : NAVY,
        }}
      >
        {value || "—"}
      </div>
    </div>
  );
}

function Bar({ pct, color }: { pct: number; color?: string }) {
  const clamped = Math.max(0, Math.min(100, pct));
  return (
    <div style={styles.barTrack}>
      <div
        style={{
          ...styles.barFill,
          width: `${clamped}%`,
          background: color || TEAL,
        }}
      />
    </div>
  );
}

function Chip({ text, tone }: { text: string; tone?: "teal" | "navy" }) {
  return (
    <span
      style={{
        ...styles.chip,
        background: tone === "navy" ? "#EDF1F5" : TEAL_TINT,
        color: tone === "navy" ? NAVY_SOFT : TEAL_DARK,
      }}
    >
      {text}
    </span>
  );
}

/** Two-tone label/value tag — a designed alternative to emoji markers. */
function TagChip({
  label,
  value,
  tone,
}: {
  label: string;
  value: string;
  tone?: "teal" | "navy";
}) {
  if (!value) return null;
  const dark = tone === "navy" ? NAVY_SOFT : TEAL_DARK;
  return (
    <span style={styles.tagChip}>
      <span style={{ ...styles.tagChipLabel, background: dark }}>{label}</span>
      <span style={styles.tagChipValue}>{value}</span>
    </span>
  );
}

/** Circular threat gauge — the one "signature" visual on the page. */
function Gauge({ score, risk }: { score: number; risk: string }) {
  const c = riskColor(risk);
  const pct = Math.max(0, Math.min(100, score));
  const r = 30;
  const circ = 2 * Math.PI * r;
  const offset = circ - (pct / 100) * circ;
  return (
    <div style={{ position: "relative", width: 72, height: 72, flexShrink: 0 }}>
      <svg width={72} height={72} viewBox="0 0 72 72">
        <circle
          cx={36}
          cy={36}
          r={r}
          fill="none"
          stroke={BORDER}
          strokeWidth={7}
        />
        <circle
          cx={36}
          cy={36}
          r={r}
          fill="none"
          stroke={c.bar}
          strokeWidth={7}
          strokeLinecap="round"
          strokeDasharray={circ}
          strokeDashoffset={offset}
          transform="rotate(-90 36 36)"
          style={{ transition: "stroke-dashoffset .6s ease" }}
        />
      </svg>
      <div
        style={{
          position: "absolute",
          inset: 0,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          flexDirection: "column",
        }}
      >
        <div
          style={{
            fontFamily: "'Poppins', sans-serif",
            fontWeight: 800,
            fontSize: 17,
            color: NAVY,
            lineHeight: 1,
          }}
        >
          {Math.round(score) || "—"}
        </div>
        <div style={{ fontSize: 8, color: MUTED, marginTop: 1 }}>SCORE</div>
      </div>
    </div>
  );
}

function TabStrip<T extends string>({
  tabs,
  active,
  onChange,
}: {
  tabs: { key: T; label: string; count?: number }[];
  active: T;
  onChange: (k: T) => void;
}) {
  return (
    <div style={styles.tabStrip}>
      {tabs.map((t) => (
        <button
          key={t.key}
          type="button"
          onClick={() => onChange(t.key)}
          style={styles.tabBtn(t.key === active)}
        >
          {t.label}
          {typeof t.count === "number" && (
            <span style={styles.tabCount(t.key === active)}>{t.count}</span>
          )}
        </button>
      ))}
    </div>
  );
}

/** Renders "## Heading" markdown-lite blocks as distinct sections instead
 * of one giant run-on paragraph with literal hash characters in it. */
function MarkdownLite({ text }: { text: string }) {
  if (!text) return null;
  const parts = text.split(/\n*##\s+/).filter(Boolean);
  // If there's no "## " structure at all, just render as a paragraph.
  if (parts.length <= 1) {
    return <p style={styles.summaryText}>{text}</p>;
  }
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
      {parts.map((part, i) => {
        const firstBreak = part.indexOf(" ");
        // First word(s) up to a period-free short run acts as the heading;
        // fall back gracefully if the model didn't format cleanly.
        const match = part.match(/^([A-Za-z &/]{3,40}?)\s+(.*)$/s);
        const heading = match ? match[1].trim() : `Section ${i + 1}`;
        const body = match ? match[2].trim() : part.trim();
        return (
          <div key={i}>
            <div style={styles.mdHeading}>{heading}</div>
            <p style={styles.summaryText}>{body || part}</p>
          </div>
        );
      })}
    </div>
  );
}

// ---------- Forecast (tabbed) ----------

function ForecastBlock({
  data,
  tab,
  setTab,
  fallbackStation,
  t,
}: {
  data: JsonValue;
  tab: "forecast" | "hotspots" | "timing" | "deployment" | "risk";
  setTab: (t: "forecast" | "hotspots" | "timing" | "deployment" | "risk") => void;
  fallbackStation: string;
  t: (typeof translations)["en"];
}) {
  const f = asRec(data);
  const knownShape =
    "overall_risk" in f ||
    "crime_forecast" in f ||
    "overall_score" in f;
  if (!knownShape) return <Register data={data} />;

  const crimeForecast = asRecArr(f.crime_forecast);
  const locations = asRecArr(f.location_intelligence);
  const timing = asRecArr(f.time_intelligence);
  const deployment = asRecArr(f.deployment_plan);
  const riskFactors = asArr(f.risk_factors).map(asStr).filter(Boolean);
  const metadata = asRec(f.metadata);
  const risk = asStr(f.overall_risk);

  return (
    <div>
      {/* Threat strip */}
      <div style={styles.threatStrip}>
        <div style={styles.threatLeft}>
          <Gauge score={asNum(f.overall_score)} risk={risk} />
          <div>
            <div style={styles.threatStation}>
              {asStr(f.station) || fallbackStation}
            </div>
            <div style={styles.threatSub}>
              {asStr(f.forecast_period) || t.forecastFallbackPeriod}
            </div>
            <div style={{ marginTop: 6 }}>
              <RiskBadge risk={risk} big />
            </div>
          </div>
        </div>
        <div style={styles.threatRight}>
          <MiniStat label={t.statConfidence} value={`${asStr(f.confidence)}%`} accent />
          <MiniStat label={t.statCrimesTracked} value={String(crimeForecast.length)} />
          {"historical_cases" in metadata && (
            <MiniStat
              label={t.statHistoricalCases}
              value={asStr(metadata.historical_cases)}
            />
          )}
          {"crime_types" in metadata && (
            <MiniStat label={t.statCrimeTypes} value={asStr(metadata.crime_types)} />
          )}
        </div>
      </div>

      {/* Tabs */}
      <div style={{ marginTop: 14 }}>
        <TabStrip
          active={tab}
          onChange={setTab}
          tabs={[
            { key: "forecast", label: t.tabForecast, count: crimeForecast.length },
            { key: "hotspots", label: t.tabHotspots, count: locations.length },
            { key: "timing", label: t.tabTiming, count: timing.length },
            { key: "deployment", label: t.tabDeployment, count: deployment.length },
            { key: "risk", label: t.tabRisk, count: riskFactors.length },
          ]}
        />

        {tab === "forecast" && (
          <div style={styles.cardGrid}>
            {crimeForecast.length === 0 && <Empty t={t} />}
            {crimeForecast.map((c, i) => (
              <div key={i} style={styles.miniCard}>
                <div style={styles.miniCardHead}>
                  <div style={styles.miniCardTitle}>{asStr(c.crime)}</div>
                  <RiskBadge risk={asStr(c.historical_risk)} />
                </div>
                <div style={{ margin: "8px 0" }}>
                  <Bar pct={asNum(c.probability)} />
                  <div style={styles.miniCardFoot}>
                    {asNum(c.probability)}% probability · {asStr(c.crime_group)}
                  </div>
                </div>
                <div style={styles.tagRow}>
                  <TagChip label={t.tagLocation} value={asStr(c.likely_location)} />
                  <TagChip label={t.tagPeak} value={asStr(c.peak_period)} />
                  <TagChip label={t.tagVehicle} value={asStr(c.suspect_vehicle)} tone="navy" />
                  <TagChip label={t.tagUnit} value={asStr(c.recommended_deployment)} tone="navy" />
                </div>
              </div>
            ))}
          </div>
        )}

        {tab === "hotspots" && (
          <div style={styles.cardGrid}>
            {locations.length === 0 && <Empty t={t} />}
            {locations.map((l, i) => (
              <div key={i} style={styles.miniCard}>
                <div style={styles.miniCardHead}>
                  <div style={styles.miniCardTitle}>{asStr(l.location)}</div>
                  <RiskBadge risk={asStr(l.risk)} />
                </div>
                <div style={styles.tagRow}>
                  <Chip text={asStr(l.dominant_crime)} />
                  <TagChip label={t.tagPeak} value={asStr(l.peak_period)} tone="navy" />
                  <Chip text={`${asStr(l.historical_cases)} ${t.casesSuffix}`} tone="navy" />
                </div>
                {l.recommended_patrol && (
                  <div style={styles.miniCardFoot}>
                    {t.patrolLabel} <b>{asStr(l.recommended_patrol)}</b>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {tab === "timing" && (
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {timing.length === 0 && <Empty t={t} />}
            {timing.map((tp, i) => (
              <div key={i} style={styles.timingRow}>
                <div style={styles.timingLabel}>{asStr(tp.time_period)}</div>
                <div style={{ flex: 1 }}>
                  <Bar pct={asNum(tp.crime_share)} />
                </div>
                <div style={styles.timingPct}>{asNum(tp.crime_share)}%</div>
                <div style={styles.timingMeta}>
                  {asStr(tp.dominant_crime)} · {asStr(tp.cases)} {t.casesSuffix}
                </div>
              </div>
            ))}
          </div>
        )}

        {tab === "deployment" && (
          <div style={styles.cardGrid}>
            {deployment.length === 0 && <Empty t={t} />}
            {deployment.map((d, i) => (
              <div key={i} style={styles.miniCard}>
                <div style={styles.miniCardHead}>
                  <div style={styles.miniCardTitle}>{asStr(d.location)}</div>
                  <RiskBadge risk={asStr(d.priority)} />
                </div>
                <div style={styles.tagRow}>
                  <Chip text={asStr(d.crime)} />
                  <TagChip label={t.tagUnit} value={asStr(d.deployment)} tone="navy" />
                </div>
                {d.reason && (
                  <div style={styles.miniCardFoot}>{asStr(d.reason)}</div>
                )}
              </div>
            ))}
          </div>
        )}

        {tab === "risk" && (
          <div style={styles.riskGrid}>
            {riskFactors.length === 0 && <Empty t={t} />}
            {riskFactors.map((r, i) => (
              <div key={i} style={styles.riskItem}>
                <span style={styles.riskDot} />
                {r}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

function Empty({ t }: { t?: (typeof translations)["en"] }) {
  return <div style={styles.emptyState}>{t ? t.noData : "No data returned."}</div>;
}

// ---------- Zone ----------

function ZoneBlock({
  data,
  t,
}: {
  data: JsonValue;
  t: (typeof translations)["en"];
}) {
  const z = asRec(data);
  const knownShape = "zone" in z || "crime_breakdown" in z || "risk" in z;
  if (!knownShape) return <Register data={data} />;

  const breakdown = asRecArr(z.crime_breakdown);
  const maxCount = Math.max(1, ...breakdown.map((b) => asNum(b.count)));
  const reasoning = asArr(z.reasoning).map(asStr).filter(Boolean);

  return (
    <div>
      <div style={styles.zoneHeader}>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <RiskBadge risk={asStr(z.risk)} big />
          <div>
            <div style={styles.miniCardTitle}>{asStr(z.zone)}</div>
            <div style={styles.panelSubtitle}>
              {asStr(z.district)} · {asStr(z.crime_count)} {t.casesSuffix}
            </div>
          </div>
        </div>
        <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
          <MiniStat label={t.zoneTopCrime} value={asStr(z.top_crime)} />
          <MiniStat label={t.zonePeakTime} value={asStr(z.peak_time)} />
          <MiniStat label={t.zoneWeather} value={asStr(z.common_weather)} />
          <MiniStat label={t.zoneRiskScore} value={asStr(z.risk_score)} accent />
        </div>
      </div>

      {breakdown.length > 0 && (
        <div style={{ marginTop: 16 }}>
          <div style={styles.subHeading}>{t.zoneCrimeBreakdown}</div>
          <div style={styles.rankGrid}>
            {breakdown.map((b, i) => (
              <div key={i} style={styles.rankRow}>
                <div style={styles.rankLabel}>{asStr(b.crime)}</div>
                <div style={{ flex: 1 }}>
                  <Bar pct={(asNum(b.count) / maxCount) * 100} color={i === 0 ? "#E07A3E" : TEAL} />
                </div>
                <div style={styles.rankCount}>{asNum(b.count)}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      <div style={styles.zoneFootRow}>
        {reasoning.length > 0 && (
          <div style={{ flex: "2 1 320px" }}>
            <div style={styles.subHeading}>{t.zoneReasoning}</div>
            <div style={styles.tagRow}>
              {reasoning.map((r, i) => (
                <Chip key={i} text={r} tone="navy" />
              ))}
            </div>
          </div>
        )}
        {(z.festival || z.linked_story) && (
          <div style={{ flex: "1 1 200px", display: "flex", gap: 8, flexWrap: "wrap" }}>
            {z.festival && <TagChip label={t.zoneFestival} value={asStr(z.festival)} />}
            {z.linked_story && <TagChip label={t.zoneCaseLink} value={asStr(z.linked_story)} tone="navy" />}
          </div>
        )}
      </div>
    </div>
  );
}

// ---------- Patterns (accordion) ----------

function PatternsBlock({
  data,
  openProfile,
  setOpenProfile,
  t,
}: {
  data: JsonValue;
  openProfile: number | null;
  setOpenProfile: (i: number | null) => void;
  t: (typeof translations)["en"];
}) {
  const p = asRec(data);
  const knownShape = "crime_behaviour_profiles" in p || "total_cases" in p;
  if (!knownShape) return <Register data={data} />;

  const profiles = asRecArr(p.crime_behaviour_profiles);
  const exec = asRec(p.executive_summary);

  return (
    <div>
      {Object.keys(exec).length > 0 && (
        <>
          <div style={styles.statGridSmall}>
            {exec.overall_threat && (
              <MiniStat label={t.patStatThreat} value={asStr(exec.overall_threat)} accent />
            )}
            {exec.dominant_crime && (
              <MiniStat label={t.patStatDominant} value={asStr(exec.dominant_crime)} />
            )}
            {exec.primary_hotspot && (
              <MiniStat label={t.patStatHotspot} value={asStr(exec.primary_hotspot)} />
            )}
            {exec.high_priority_alerts !== undefined && (
              <MiniStat label={t.patStatHighPriority} value={asStr(exec.high_priority_alerts)} />
            )}
          </div>
          {exec.summary && (
            <p style={{ ...styles.summaryText, marginTop: 10 }}>
              {asStr(exec.summary)}
            </p>
          )}
        </>
      )}

      {profiles.length > 0 && (
        <div style={{ marginTop: 12, display: "flex", flexDirection: "column", gap: 6 }}>
          <div style={styles.subHeading}>{t.behaviourProfiles}</div>
          {profiles.map((pr, i) => {
            const open = openProfile === i;
            const locations = asArr(pr.preferred_locations).map(asStr);
            const sections = asArr(pr.act_sections).map(asStr);
            return (
              <div key={i} style={styles.accordion}>
                <button
                  type="button"
                  style={styles.accordionHead}
                  onClick={() => setOpenProfile(open ? null : i)}
                >
                  <span style={{ display: "flex", alignItems: "center", gap: 8 }}>
                    <span style={styles.accordionCaret(open)}>▸</span>
                    <b style={{ color: NAVY }}>{asStr(pr.crime) || asStr(pr.pattern_name)}</b>
                    <span style={{ color: MUTED, fontSize: 11.5 }}>
                      {asStr(pr.modus_operandi)}
                    </span>
                  </span>
                  <span style={{ display: "flex", alignItems: "center", gap: 6 }}>
                    {pr.confidence !== undefined && (
                      <span style={styles.confBadge}>{asStr(pr.confidence)}% {t.confSuffix}</span>
                    )}
                    <RiskBadge risk={asStr(pr.historical_risk)} />
                  </span>
                </button>
                {open && (
                  <div style={styles.accordionBody}>
                    <div style={styles.statGridSmall}>
                      <MiniStat label={t.patPatternType} value={asStr(pr.pattern_type)} />
                      <MiniStat label={t.patFrequency} value={asStr(pr.frequency)} />
                      <MiniStat label={t.patSuspectGroup} value={asStr(pr.suspect_group)} />
                      <MiniStat label={t.patSuspectVehicle} value={asStr(pr.suspect_vehicle)} />
                      <MiniStat label={t.patLinkedCluster} value={asStr(pr.linked_cluster)} />
                      <MiniStat label={t.patPatrolPriority} value={asStr(pr.patrol_priority)} />
                    </div>
                    {locations.length > 0 && (
                      <div style={{ marginTop: 10 }}>
                        <div style={styles.subHeading}>{t.patPreferredLocations}</div>
                        <div style={styles.tagRow}>
                          {locations.map((l, j) => (
                            <Chip key={j} text={l} />
                          ))}
                        </div>
                      </div>
                    )}
                    {sections.length > 0 && (
                      <div style={{ marginTop: 10 }}>
                        <div style={styles.subHeading}>{t.patActSections}</div>
                        <div style={styles.tagRow}>
                          {sections.map((s, j) => (
                            <Chip key={j} text={s} tone="navy" />
                          ))}
                        </div>
                      </div>
                    )}
                    {pr.recommended_action && (
                      <div style={{ ...styles.miniCardFoot, marginTop: 10 }}>
                        <b>{t.patRecommended}</b> {asStr(pr.recommended_action)}
                      </div>
                    )}
                    {pr.operational_alert && (
                      <div style={styles.alertNote}>
                        <div style={styles.alertLabel}>{t.patOperationalAlert}</div>
                        {asStr(pr.operational_alert)}
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

// ---------- Anomalies ----------

function AnomaliesBlock({ data }: { data: JsonValue }) {
  const a = asRec(data);
  const knownShape = "anomalies" in a || "analysis_window" in a;
  if (!knownShape) return <Register data={data} />;

  const list = asRecArr(a.anomalies);
  const exec = asRec(a.executive_summary);

  return (
    <div>
      {Object.keys(exec).length > 0 && (
        <div style={styles.statGridSmall}>
          {exec.overall_threat && (
            <MiniStat label="Threat" value={asStr(exec.overall_threat)} accent />
          )}
          {exec.critical_alerts !== undefined && (
            <MiniStat label="Critical" value={asStr(exec.critical_alerts)} />
          )}
          {exec.high_alerts !== undefined && (
            <MiniStat label="High" value={asStr(exec.high_alerts)} />
          )}
          {exec.total_anomalies !== undefined && (
            <MiniStat label="Total" value={asStr(exec.total_anomalies)} />
          )}
        </div>
      )}
      {exec.summary && (
        <p style={{ ...styles.summaryText, marginTop: 10 }}>{asStr(exec.summary)}</p>
      )}

      {list.length > 0 ? (
        <div style={{ marginTop: 12, display: "flex", flexDirection: "column", gap: 6 }}>
          {list.map((an, i) => (
            <div key={i} style={styles.miniCard}>
              <div style={styles.miniCardHead}>
                <div style={styles.miniCardTitle}>{asStr(an.crime)}</div>
                <RiskBadge risk={asStr(an.severity) || asStr(an.type)} />
              </div>
              <div style={styles.miniCardFoot}>
                {asStr(an.type)} · {asStr(an.change_percent)}% change
              </div>
              {an.reason && <div style={styles.miniCardFoot}>{asStr(an.reason)}</div>}
            </div>
          ))}
        </div>
      ) : (
        Object.keys(exec).length === 0 && <Empty />
      )}

      {a.explainability && (
        <div style={{ marginTop: 10, fontSize: 11.5, color: MUTED, fontStyle: "italic" }}>
          {asStr(a.explainability)}
        </div>
      )}
    </div>
  );
}

function ShieldIcon({
  size = 20,
  color = "#FFFFFF",
}: {
  size?: number;
  color?: string;
}) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <path
        d="M12 3l7 3v6c0 4.5-3 7.7-7 9-4-1.3-7-4.5-7-9V6l7-3z"
        stroke={color}
        strokeWidth="1.7"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function GlobeIcon({
  size = 13,
  color = "#0E8C8C",
}: {
  size?: number;
  color?: string;
}) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <circle cx="12" cy="12" r="10" stroke={color} strokeWidth="2" />
      <line x1="2" y1="12" x2="22" y2="12" stroke={color} strokeWidth="2" />
      <path
        d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"
        stroke={color}
        strokeWidth="2"
      />
    </svg>
  );
}

function NavIcon({ name, color }: { name: string; color: string }) {
  const common = {
    width: 17,
    height: 17,
    viewBox: "0 0 24 24",
    fill: "none" as const,
  };
  switch (name) {
    case "grid":
      return (
        <svg {...common}>
          <rect x="4" y="4" width="7" height="7" rx="1.4" stroke={color} strokeWidth="1.7" />
          <rect x="13" y="4" width="7" height="7" rx="1.4" stroke={color} strokeWidth="1.7" />
          <rect x="4" y="13" width="7" height="7" rx="1.4" stroke={color} strokeWidth="1.7" />
          <rect x="13" y="13" width="7" height="7" rx="1.4" stroke={color} strokeWidth="1.7" />
        </svg>
      );
    case "case":
      return (
        <svg {...common}>
          <rect x="3" y="8" width="18" height="12" rx="1.5" stroke={color} strokeWidth="1.7" />
          <path d="M8 8V6a2 2 0 012-2h4a2 2 0 012 2v2" stroke={color} strokeWidth="1.7" />
        </svg>
      );
    case "map":
      return (
        <svg {...common}>
          <path d="M9 4l-5 2v14l5-2 6 2 5-2V4l-5 2-6-2z" stroke={color} strokeWidth="1.6" strokeLinejoin="round" />
          <path d="M9 4v14M15 6v14" stroke={color} strokeWidth="1.6" />
        </svg>
      );
    case "chart":
      return (
        <svg {...common}>
          <path d="M4 20V10M11 20V4M18 20v-7" stroke={color} strokeWidth="1.9" strokeLinecap="round" />
        </svg>
      );
    case "bolt":
      return (
        <svg {...common}>
          <path d="M13 2L4 14h6l-1 8 9-12h-6l1-8z" stroke={color} strokeWidth="1.6" strokeLinejoin="round" />
        </svg>
      );
    case "gear":
      return (
        <svg {...common}>
          <circle cx="12" cy="12" r="3" stroke={color} strokeWidth="1.6" />
          <path
            d="M19 12a7 7 0 00-.1-1.2l2-1.5-2-3.4-2.3.9a7 7 0 00-2-1.2L14.2 3H9.8l-.4 2.6a7 7 0 00-2 1.2l-2.3-.9-2 3.4 2 1.5A7 7 0 005 12c0 .4 0 .8.1 1.2l-2 1.5 2 3.4 2.3-.9c.6.5 1.3.9 2 1.2l.4 2.6h4.4l.4-2.6c.7-.3 1.4-.7 2-1.2l2.3.9 2-3.4-2-1.5c.1-.4.1-.8.1-1.2z"
            stroke={color}
            strokeWidth="1.3"
            strokeLinejoin="round"
          />
        </svg>
      );
    case "logout":
      return (
        <svg {...common}>
          <path d="M9 4H5a1 1 0 00-1 1v14a1 1 0 001 1h4" stroke={color} strokeWidth="1.6" strokeLinecap="round" />
          <path d="M15 16l4-4-4-4M19 12H9" stroke={color} strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      );
    default:
      return null;
  }
}

// ---------- Styles (matching KAVACH's navy/teal system) ----------

const NAVY = "#152A43";
const NAVY_DEEP = "#0E2438";
const NAVY_SOFT = "#2C4260";
const TEAL = "#0E8C8C";
const TEAL_DARK = "#0A6E6E";
const TEAL_TINT = "#E1F5F5";
const TEXT = "#5B6B7A";
const MUTED = "#8A97A3";
const BORDER = "#E3E9EC";
const BG_SECTION = "#EAF2F5";
const RED = "#C94B4B";

const keyframes = `@keyframes xaiSpin { to { transform: rotate(360deg); } }`;

const styles = {
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "flex-start",
    background: BG_SECTION,
    fontFamily: "'Inter', 'Segoe UI', system-ui, sans-serif",
  } as React.CSSProperties,

  sidebar: {
    width: "236px",
    flexShrink: 0,
    alignSelf: "flex-start",
    background: `linear-gradient(180deg, ${NAVY} 0%, ${NAVY_DEEP} 100%)`,
    display: "flex",
    flexDirection: "column",
    padding: "24px 18px",
    position: "sticky" as const,
    top: 0,
    height: "100vh",
    overflowY: "auto" as const,
  } as React.CSSProperties,

  sidebarLogoRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "0 8px",
    marginBottom: 30,
  } as React.CSSProperties,
  sidebarLogoIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: `linear-gradient(150deg, ${TEAL}, ${NAVY})`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  } as React.CSSProperties,
  sidebarLogoTitle: {
    fontFamily: "'Poppins', 'Segoe UI', sans-serif",
    fontSize: 16,
    fontWeight: 700,
    color: "#FFFFFF",
  } as React.CSSProperties,
  sidebarLogoSub: {
    fontSize: 9.5,
    letterSpacing: "0.08em",
    color: "rgba(255,255,255,0.45)",
    marginTop: 1,
  } as React.CSSProperties,

  navList: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    flex: 1,
  } as React.CSSProperties,
  navItem: (active: boolean): React.CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 11,
    padding: "10px 12px",
    borderRadius: 8,
    border: "none",
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    fontSize: 13.5,
    fontWeight: active ? 600 : 500,
    background: active ? "rgba(14,140,140,0.22)" : "transparent",
    color: active ? "#FFFFFF" : "rgba(255,255,255,0.65)",
    textAlign: "left",
    transition: "background 0.15s ease",
  }),

  sidebarStatusCard: {
    marginTop: "auto",
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 10,
    padding: "12px 12px",
  } as React.CSSProperties,
  sidebarStatusRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    fontWeight: 600,
    color: "#FFFFFF",
  } as React.CSSProperties,
  sidebarStatusDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "#3FD17B",
    boxShadow: "0 0 0 3px rgba(63,209,123,0.18)",
    flexShrink: 0,
  } as React.CSSProperties,
  sidebarStatusSub: {
    fontSize: 10.5,
    color: "rgba(255,255,255,0.45)",
    marginTop: 5,
    marginLeft: 15,
  } as React.CSSProperties,

  sidebarFooter: {
    borderTop: "1px solid rgba(255,255,255,0.12)",
    paddingTop: 16,
    marginTop: 12,
  } as React.CSSProperties,
  sidebarOfficerRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "0 8px",
    marginBottom: 12,
  } as React.CSSProperties,
  sidebarAvatar: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "rgba(255,255,255,0.12)",
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  } as React.CSSProperties,
  sidebarOfficerName: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "#FFFFFF",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } as React.CSSProperties,
  sidebarOfficerBadge: {
    fontSize: 11,
    color: "rgba(255,255,255,0.5)",
    marginTop: 1,
  } as React.CSSProperties,
  logoutBtn: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 9,
    padding: "9px 12px",
    background: "rgba(255,255,255,0.06)",
    border: "none",
    borderRadius: 8,
    color: "rgba(255,255,255,0.8)",
    fontSize: 12.5,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
  } as React.CSSProperties,

  main: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
  } as React.CSSProperties,

  topbar: {
    background: "#FFFFFF",
    borderBottom: `1px solid ${BORDER}`,
    padding: "18px 32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  } as React.CSSProperties,
  topbarTitle: {
    fontFamily: "'Poppins', 'Segoe UI', sans-serif",
    fontSize: 18,
    fontWeight: 600,
    color: NAVY,
  } as React.CSSProperties,
  topbarSub: {
    fontSize: 12.5,
    color: TEXT,
    marginTop: 2,
  } as React.CSSProperties,
  officerChipRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  } as React.CSSProperties,
  langBtn: {
    background: "transparent",
    color: TEAL,
    border: `1px solid ${TEAL}`,
    borderRadius: 20,
    padding: "5px 12px",
    fontFamily: "'Inter', sans-serif",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
  } as React.CSSProperties,
  officerBadge: {
    fontSize: 11,
    padding: "4px 9px",
    background: TEAL_TINT,
    color: TEAL_DARK,
    borderRadius: 5,
    fontWeight: 600,
  } as React.CSSProperties,
  officerName: {
    fontSize: 13,
    color: "#374151",
    fontWeight: 500,
  } as React.CSSProperties,

  body: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 18,
    padding: "24px 32px",
    overflowY: "auto",
  } as React.CSSProperties,

  twoCol: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 18,
  } as React.CSSProperties,
  threeCol: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: 18,
  } as React.CSSProperties,

  panel: {
    background: "#FFFFFF",
    border: `1px solid ${BORDER}`,
    borderRadius: 14,
    padding: 18,
    minWidth: 0,
  } as React.CSSProperties,
  panelTitle: {
    fontFamily: "'Poppins', 'Segoe UI', sans-serif",
    fontSize: 14,
    fontWeight: 700,
    color: NAVY,
  } as React.CSSProperties,
  panelSubtitle: {
    fontSize: 11.5,
    color: MUTED,
    marginTop: 2,
  } as React.CSSProperties,

  stationBar: { display: "flex", gap: 10 } as React.CSSProperties,
  stationInput: {
    flex: 1,
    padding: "11px 14px",
    borderRadius: 8,
    border: `1px solid ${BORDER}`,
    fontSize: 13,
    fontFamily: "'Inter', sans-serif",
    color: "#374151",
    background: "#FFFFFF",
  } as React.CSSProperties,
  primaryBtn: {
    padding: "11px 18px",
    borderRadius: 8,
    border: "none",
    background: TEAL,
    color: "#FFFFFF",
    fontWeight: 700,
    fontSize: 13,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    whiteSpace: "nowrap",
  } as React.CSSProperties,
  secondaryBtn: {
    padding: "11px 18px",
    borderRadius: 8,
    border: `1px solid ${TEAL}`,
    background: "#FFFFFF",
    color: TEAL_DARK,
    fontWeight: 700,
    fontSize: 13,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    whiteSpace: "nowrap",
  } as React.CSSProperties,

  emptyState: {
    padding: "16px",
    textAlign: "center" as const,
    color: MUTED,
    fontSize: 12.5,
    background: "#FFFFFF",
    border: `1px dashed ${BORDER}`,
    borderRadius: 10,
  },

  loadingState: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    color: MUTED,
    fontSize: 12,
    padding: "10px 2px",
  } as React.CSSProperties,
  spinner: {
    width: 16,
    height: 16,
    border: `2px solid ${TEAL_TINT}`,
    borderTop: `2px solid ${TEAL}`,
    borderRadius: "50%",
    animation: "xaiSpin .8s linear infinite",
  } as React.CSSProperties,
  errorBox: {
    padding: "10px 12px",
    background: "#FBEBEA",
    color: RED,
    fontSize: 12,
    lineHeight: 1.5,
    borderRadius: 8,
  } as React.CSSProperties,

  registerGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(150px, 1fr))",
    gap: 8,
  } as React.CSSProperties,
  registerCell: {
    background: BG_SECTION,
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    padding: "8px 10px",
    minWidth: 0,
  } as React.CSSProperties,
  evidenceCardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
    gap: 10,
  } as React.CSSProperties,
  evidenceCard: {
    background: "#FFFFFF",
    border: `1px solid ${BORDER}`,
    borderRadius: 10,
    padding: 10,
    minWidth: 0,
  } as React.CSSProperties,
  evidenceCardIndex: {
    fontSize: 9.5,
    fontWeight: 800,
    color: TEAL_DARK,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    marginBottom: 8,
  } as React.CSSProperties,
  evidenceTag: {
    fontSize: 11,
    fontWeight: 600,
    color: NAVY_SOFT,
    background: BG_SECTION,
    border: `1px solid ${BORDER}`,
    padding: "3px 9px",
    borderRadius: 999,
  } as React.CSSProperties,
  registerLabel: {
    fontSize: 9.5,
    color: MUTED,
    textTransform: "uppercase" as const,
    letterSpacing: "0.04em",
    marginBottom: 3,
  },
  registerValue: {
    fontSize: 13,
    fontWeight: 600,
    color: NAVY,
    wordBreak: "break-word" as const,
  },
  registerNested: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } as React.CSSProperties,
  nestedRow: {
    borderBottom: `1px solid ${BORDER}`,
    paddingBottom: 8,
  } as React.CSSProperties,
  nestedSection: {
    borderBottom: `1px solid ${BORDER}`,
    paddingBottom: 14,
  } as React.CSSProperties,
  nestedIndent: {
    marginTop: 6,
    marginLeft: 10,
    borderLeft: `2px solid ${TEAL_TINT}`,
    paddingLeft: 10,
  } as React.CSSProperties,

  aiSection: {
    background: "#FFFFFF",
    border: `1px solid ${BORDER}`,
    borderRadius: 14,
    padding: 18,
  } as React.CSSProperties,
  aiSectionHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 14,
    flexWrap: "wrap" as const,
    marginBottom: 14,
  },
  resultsTitle: {
    fontFamily: "'Poppins', 'Segoe UI', sans-serif",
    fontSize: 16,
    fontWeight: 700,
    color: NAVY,
  } as React.CSSProperties,
  disclaimer: {
    fontSize: 11,
    color: MUTED,
    marginTop: 4,
    maxWidth: "48ch",
    lineHeight: 1.5,
  } as React.CSSProperties,

  aiCard: {
    background: BG_SECTION,
    border: `1px solid ${BORDER}`,
    borderRadius: 10,
    padding: 16,
    marginTop: 12,
  } as React.CSSProperties,
  aiCardLabel: {
    fontSize: 10.5,
    fontWeight: 700,
    color: TEAL_DARK,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    marginBottom: 8,
  },
  summaryText: {
    fontSize: 13.5,
    lineHeight: 1.7,
    color: NAVY_SOFT,
    margin: 0,
  } as React.CSSProperties,
  reportText: {
    fontSize: 13.5,
    lineHeight: 1.75,
    color: NAVY_SOFT,
    whiteSpace: "pre-wrap" as const,
    margin: 0,
  },

  evidenceToggle: {
    marginTop: 12,
    border: `1px solid ${BORDER}`,
    background: "#FFFFFF",
    color: TEXT,
    cursor: "pointer",
    padding: "6px 12px",
    borderRadius: 6,
    fontSize: 11.5,
    fontWeight: 600,
  } as React.CSSProperties,
  evidenceBox: {
    marginTop: 12,
    padding: 14,
    background: "#FFFFFF",
    border: `1px solid ${BORDER}`,
    borderRadius: 10,
    maxHeight: 480,
    overflowY: "auto" as const,
  } as React.CSSProperties,
  evidenceHeading: {
    fontSize: 10.5,
    fontWeight: 700,
    color: TEAL_DARK,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    marginBottom: 12,
  } as React.CSSProperties,

  // ---- New: threat strip / gauge ----
  threatStrip: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap" as const,
    gap: 16,
    padding: "6px 4px 4px",
  },
  threatLeft: {
    display: "flex",
    alignItems: "center",
    gap: 14,
  } as React.CSSProperties,
  threatRight: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap" as const,
  },
  threatStation: {
    fontFamily: "'Poppins', 'Segoe UI', sans-serif",
    fontSize: 16,
    fontWeight: 700,
    color: NAVY,
  } as React.CSSProperties,
  threatSub: {
    fontSize: 11.5,
    color: MUTED,
    marginTop: 1,
  } as React.CSSProperties,

  miniStat: {
    background: BG_SECTION,
    border: `1px solid ${BORDER}`,
    borderRadius: 9,
    padding: "7px 12px",
    minWidth: 82,
  } as React.CSSProperties,
  miniStatLabel: {
    fontSize: 9,
    color: MUTED,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    marginBottom: 2,
  },
  miniStatValue: {
    fontSize: 14,
    fontWeight: 800,
    fontFamily: "'Poppins', 'Segoe UI', sans-serif",
  } as React.CSSProperties,
  statGridSmall: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(110px, 1fr))",
    gap: 8,
  } as React.CSSProperties,

  // ---- Tabs ----
  tabStrip: {
    display: "flex",
    gap: 4,
    borderBottom: `1px solid ${BORDER}`,
    marginBottom: 12,
    flexWrap: "wrap" as const,
  },
  tabBtn: (active: boolean): React.CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "8px 12px",
    border: "none",
    background: "transparent",
    borderBottom: active ? `2px solid ${TEAL}` : "2px solid transparent",
    color: active ? TEAL_DARK : TEXT,
    fontWeight: active ? 700 : 500,
    fontSize: 12.5,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    marginBottom: -1,
  }),
  tabCount: (active: boolean): React.CSSProperties => ({
    fontSize: 10,
    padding: "1px 6px",
    borderRadius: 999,
    background: active ? TEAL_TINT : BG_SECTION,
    color: active ? TEAL_DARK : MUTED,
    fontWeight: 700,
  }),

  // ---- Cards / grids ----
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
    gap: 10,
  } as React.CSSProperties,
  miniCard: {
    background: BG_SECTION,
    border: `1px solid ${BORDER}`,
    borderRadius: 10,
    padding: 12,
  } as React.CSSProperties,
  miniCardHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  } as React.CSSProperties,
  miniCardTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: NAVY,
  } as React.CSSProperties,
  miniCardFoot: {
    fontSize: 11,
    color: TEXT,
    marginTop: 4,
    lineHeight: 1.5,
  } as React.CSSProperties,

  tagRow: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 6,
    marginTop: 6,
  },
  chip: {
    fontSize: 10.5,
    padding: "3px 9px",
    borderRadius: 999,
    fontWeight: 600,
    whiteSpace: "nowrap" as const,
  } as React.CSSProperties,

  tagChip: {
    display: "inline-flex",
    alignItems: "stretch",
    borderRadius: 999,
    overflow: "hidden",
    border: `1px solid ${BORDER}`,
  } as React.CSSProperties,
  tagChipLabel: {
    fontSize: 8.5,
    fontWeight: 800,
    color: "#FFFFFF",
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    padding: "4px 8px",
    display: "flex",
    alignItems: "center",
  } as React.CSSProperties,
  tagChipValue: {
    fontSize: 11,
    fontWeight: 600,
    color: NAVY,
    background: "#FFFFFF",
    padding: "4px 10px",
    display: "flex",
    alignItems: "center",
    whiteSpace: "nowrap" as const,
  } as React.CSSProperties,

  zoneHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap" as const,
    gap: 16,
  } as React.CSSProperties,
  zoneFootRow: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 24,
    marginTop: 18,
    paddingTop: 14,
    borderTop: `1px solid ${BORDER}`,
  } as React.CSSProperties,
  rankGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: "7px 24px",
  } as React.CSSProperties,

  barTrack: {
    width: "100%",
    height: 6,
    borderRadius: 4,
    background: "#FFFFFF",
    overflow: "hidden",
  } as React.CSSProperties,
  barFill: {
    height: "100%",
    borderRadius: 4,
    transition: "width .5s ease",
  } as React.CSSProperties,

  // ---- Timing rows ----
  timingRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "6px 2px",
  } as React.CSSProperties,
  timingLabel: {
    width: 70,
    fontSize: 12,
    fontWeight: 700,
    color: NAVY,
    flexShrink: 0,
  } as React.CSSProperties,
  timingPct: {
    width: 34,
    fontSize: 11.5,
    fontWeight: 700,
    color: TEAL_DARK,
    flexShrink: 0,
    textAlign: "right" as const,
  },
  timingMeta: {
    width: 160,
    fontSize: 10.5,
    color: MUTED,
    flexShrink: 0,
    textAlign: "right" as const,
  },

  // ---- Risk factors ----
  riskGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: 6,
  } as React.CSSProperties,
  riskItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 7,
    fontSize: 12,
    color: NAVY_SOFT,
    lineHeight: 1.5,
    background: BG_SECTION,
    borderRadius: 8,
    padding: "8px 10px",
  } as React.CSSProperties,
  riskDot: {
    width: 5,
    height: 5,
    borderRadius: "50%",
    background: "#E07A3E",
    marginTop: 6,
    flexShrink: 0,
  } as React.CSSProperties,

  // ---- Ranking rows (crime breakdown) ----
  rankRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  } as React.CSSProperties,
  rankLabel: {
    width: 110,
    fontSize: 11.5,
    color: NAVY_SOFT,
    fontWeight: 600,
    flexShrink: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  rankCount: {
    width: 28,
    fontSize: 11.5,
    fontWeight: 700,
    color: NAVY,
    textAlign: "right" as const,
    flexShrink: 0,
  },

  subHeading: {
    fontSize: 10.5,
    fontWeight: 700,
    color: TEAL_DARK,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    marginBottom: 6,
  },

  // ---- Accordion (behaviour profiles) ----
  accordion: {
    border: `1px solid ${BORDER}`,
    borderRadius: 10,
    overflow: "hidden",
    background: "#FFFFFF",
  } as React.CSSProperties,
  accordionHead: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    padding: "10px 12px",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    fontSize: 12.5,
    textAlign: "left" as const,
  },
  accordionCaret: (open: boolean): React.CSSProperties => ({
    display: "inline-block",
    transition: "transform .15s ease",
    transform: open ? "rotate(90deg)" : "rotate(0deg)",
    color: TEAL,
    fontSize: 11,
  }),
  accordionBody: {
    padding: "0 12px 14px",
    borderTop: `1px solid ${BORDER}`,
    paddingTop: 12,
  } as React.CSSProperties,
  confBadge: {
    fontSize: 10,
    fontWeight: 700,
    color: TEAL_DARK,
    background: TEAL_TINT,
    padding: "2px 7px",
    borderRadius: 999,
  } as React.CSSProperties,
  alertNote: {
    marginTop: 10,
    fontSize: 11,
    color: "#A13D1F",
    background: "#FCEEE4",
    padding: "9px 12px",
    borderRadius: 7,
    borderLeft: "3px solid #E07A3E",
    lineHeight: 1.5,
  } as React.CSSProperties,
  alertLabel: {
    fontSize: 9.5,
    fontWeight: 800,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    marginBottom: 3,
    color: "#A13D1F",
  },

  mdHeading: {
    fontSize: 11.5,
    fontWeight: 800,
    color: TEAL_DARK,
    textTransform: "uppercase" as const,
    letterSpacing: "0.04em",
    marginBottom: 4,
  },
};